"""init

Revision ID: adf189395b21
Revises: 
Create Date: 2026-08-07 10:23:49.062894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf189395b21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_token_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token_key', sa.String(length=100), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('source_field', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_key')
    )
    op.create_table('deleted_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restore_token', sa.String(length=64), nullable=True),
    sa.Column('permanent_delete_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('branding_color', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('subscription_tier', sa.Enum('free', 'pro', 'enterprise', name='subscriptiontierenum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_table('permanent_delete_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recycle_bin',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('record_data', sa.JSON(), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('restore_expires_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yearly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_contracts', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_views',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_rejection_reasons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clause_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_jurisdictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('tax_laws', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('integration_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('api_secret', sa.String(length=255), nullable=True),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'slack', 'in_app', 'sms', name='notificationchannelenum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type')
    )
    op.create_table('organization_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('enable_ai', sa.Boolean(), nullable=True),
    sa.Column('enable_esign', sa.Boolean(), nullable=True),
    sa.Column('enable_client_portal', sa.Boolean(), nullable=True),
    sa.Column('enable_audit_logs', sa.Boolean(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_contracts', sa.Integer(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscriptionstatusenum'), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'retrying', name='webhookeventstatusenum'), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.Enum('client_customer', 'vendor_supplier', 'internal_entity', 'partner', name='entitytypeenum'), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('jurisdiction_id', sa.BigInteger(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['client_jurisdictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_template_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['contract_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('integration_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.BigInteger(), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integration_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_forms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('can_create', sa.Boolean(), nullable=True),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_update', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_approve', sa.Boolean(), nullable=True),
    sa.Column('can_assign', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_clauses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('standard_text', sa.Text(), nullable=True),
    sa.Column('fallback_text', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevelenum'), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['clause_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_historical_benchmarks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_type_id', sa.BigInteger(), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_queries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_workflows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_parallel', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Enum('insert', 'update', 'delete', 'view', 'export', 'approve', 'reject', 'sign', name='auditactionenum'), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clause_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('clause_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clause_id'], ['template_clauses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_addresses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('address_type', sa.Enum('billing', 'shipping', 'registered', name='addresstypeenum'), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_type_approval_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_type_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('min_approvers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_type_custom_fields',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_type_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'number', 'date', 'dropdown', 'checkbox'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['request_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_publication_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='formstatusenum'), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('published_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['request_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['request_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'slack', 'in_app', 'sms', name='notificationchannelenum'), nullable=True),
    sa.Column('status', sa.Enum('sent', 'failed', 'pending', name='notificationstatusenum'), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Enum('email', 'slack', 'in_app', 'sms', name='notificationchannelenum'), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('form_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'dependency_gathering', 'drafting_in_progress', 'internal_review', 'approved_ready', 'client_negotiation', 're_drafting', 'executed', 'archived', name='requeststatusenum'), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='priorityenum'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['request_forms.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('user_login_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('login_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('approval_workflow_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.BigInteger(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('min_approvers', sa.Integer(), nullable=True),
    sa.Column('can_skip', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log_details',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_manager_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('note_type', sa.Enum('blocker', 'risk', 'decision', 'general', name='notetypeenum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_type_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=True),
    sa.Column('current_version_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('drafting', 'internal_review', 'approved', 'negotiation', 'executed', 'archived', name='contractstatusenum'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    op.create_table('dependency_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('task_objective', sa.Text(), nullable=False),
    sa.Column('sla_deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue', name='dependencytaskstatusenum'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_fields',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'textarea', 'email', 'phone', 'date', 'datetime', 'currency', 'number', 'dropdown', 'multiselect', 'checkbox', 'file', 'rich_text', 'radio', name='fieldtypeenum'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['form_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['request_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_clone_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('original_request_id', sa.BigInteger(), nullable=False),
    sa.Column('new_request_id', sa.BigInteger(), nullable=False),
    sa.Column('cloned_by', sa.BigInteger(), nullable=False),
    sa.Column('cloned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cloned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['original_request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.Enum('internal', 'client', 'system', name='commenttypeenum'), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('changed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_content', sa.Text(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amendments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('amendment_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'executed', name='amendmentstatusenum'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archived_contracts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('archive_reason', sa.String(length=255), nullable=True),
    sa.Column('archived_by', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('retention_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_contracts_link',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'contract_id')
    )
    op.create_table('client_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('client_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('section_reference', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('pricing', 'timeline', 'scope', 'legal', 'other', name='feedbackcategoryenum'), nullable=False),
    sa.Column('proposed_wording', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'counter_offered', name='feedbackstatusenum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_contact_id'], ['client_contacts.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_portal_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('client_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_contact_id'], ['client_contacts.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('compliance_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('generated_by', sa.BigInteger(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('token_key', sa.String(length=100), nullable=False),
    sa.Column('token_value', sa.Text(), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('version_label', sa.Enum('draft', 'internal_draft', 'approved', 'executed', 'archived', name='versionlabelenum'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['dependency_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['dependency_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('feasibility', sa.Enum('feasible', 'feasible_with_risks', 'not_feasible', name='feasibilityenum'), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=True),
    sa.Column('internal_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_delivery', sa.Date(), nullable=True),
    sa.Column('submitted_by', sa.BigInteger(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['dependency_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expiration_tracking',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('termination_notice_sent', sa.Boolean(), nullable=True),
    sa.Column('notice_sent_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expiring_soon', 'expired', 'terminated', name='expirationstatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_field_dependencies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.BigInteger(), nullable=False),
    sa.Column('dependent_field_id', sa.BigInteger(), nullable=False),
    sa.Column('condition_type', sa.Enum('equals', 'not_equals', 'contains', 'not_contains', 'greater_than', 'less_than', name='conditiontypeenum'), nullable=False),
    sa.Column('condition_value', sa.Text(), nullable=True),
    sa.Column('action', sa.Enum('show', 'hide', 'enable', 'disable', name='actionenum'), nullable=True),
    sa.ForeignKeyConstraint(['dependent_field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_field_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.BigInteger(), nullable=False),
    sa.Column('option_label', sa.String(length=255), nullable=False),
    sa.Column('option_value', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_field_validations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.BigInteger(), nullable=False),
    sa.Column('validation_type', sa.Enum('required', 'min_length', 'max_length', 'min_value', 'max_value', 'regex', 'email', 'phone', 'custom', name='validationtypeenum'), nullable=False),
    sa.Column('validation_value', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('obligation_type', sa.Enum('deliverable', 'report', 'audit', 'support', 'compliance', name='obligationtypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue', name='obligationstatusenum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portal_access',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('client_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_comment', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_sign', sa.Boolean(), nullable=True),
    sa.Column('can_download', sa.Boolean(), nullable=True),
    sa.Column('granted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['client_contact_id'], ['client_contacts.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portal_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('client_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Enum('viewed', 'downloaded', 'commented', 'requested_change', 'signed', 'rejected', name='portalactiontypeenum'), nullable=False),
    sa.Column('action_details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('action_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_contact_id'], ['client_contacts.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renewal_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_type', sa.Enum('days_30', 'days_14', 'days_7', 'days_1', name='alerttypeenum'), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_to', sa.BigInteger(), nullable=True),
    sa.Column('sent_via', sa.Enum('email', 'slack', 'in_app', name='alertsentviaenum'), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renewals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('renewal_terms', sa.Text(), nullable=True),
    sa.Column('renewal_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'negotiating', 'renewed', 'expired', name='renewalstatusenum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_field_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('field_id', sa.BigInteger(), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('field_value_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amendment_approvals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amendment_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='amendmentapprovalstatusenum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['amendment_id'], ['amendments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amendment_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amendment_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['amendment_id'], ['amendments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'skipped', name='approvalstatusenum'), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['approval_workflow_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['contract_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('section_reference', sa.String(length=255), nullable=True),
    sa.Column('comment_type', sa.Enum('internal', 'reviewer', 'client', name='contractcommenttypeenum'), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['contract_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_diffs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('from_version_id', sa.BigInteger(), nullable=False),
    sa.Column('to_version_id', sa.BigInteger(), nullable=False),
    sa.Column('diff_content', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_version_id'], ['contract_versions.id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['contract_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_edits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['contract_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_version_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('tagged_by', sa.BigInteger(), nullable=True),
    sa.Column('tagged_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['contract_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.Column('milestone_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'pending_client', 'completed', 'delayed', name='milestonestatusenum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['contract_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiation_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.BigInteger(), nullable=False),
    sa.Column('response_type', sa.Enum('accept', 'reject', 'counter_offer', name='negotiationresponsetypeenum'), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.BigInteger(), nullable=True),
    sa.Column('responded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['client_feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('signer_id', sa.BigInteger(), nullable=True),
    sa.Column('signer_email', sa.String(length=255), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('signature_provider', sa.Enum('docusign', 'adobesign', 'builtin', name='signatureproviderenum'), nullable=True),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'viewed', 'signed', 'declined', 'expired', name='signaturestatusenum'), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('signed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['contract_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', name='decisionenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signature_hash', sa.String(length=255), nullable=True),
    sa.Column('decision_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone_status_updates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signatures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signature_request_id', sa.BigInteger(), nullable=False),
    sa.Column('signer_email', sa.String(length=255), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('signature_hash', sa.String(length=255), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['signature_request_id'], ['signature_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signatory_verification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signature_id', sa.BigInteger(), nullable=False),
    sa.Column('verification_method', sa.Enum('otp', 'biometric', '_2fa', 'certificate', name='verificationmethodenum'), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['signature_id'], ['signatures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signatory_verification')
    op.drop_table('signatures')
    op.drop_table('milestone_status_updates')
    op.drop_table('approval_decisions')
    op.drop_table('signature_requests')
    op.drop_table('negotiation_responses')
    op.drop_table('milestones')
    op.drop_table('contract_version_tags')
    op.drop_table('contract_edits')
    op.drop_table('contract_diffs')
    op.drop_table('contract_comments')
    op.drop_table('approval_tasks')
    op.drop_table('amendment_versions')
    op.drop_table('amendment_approvals')
    op.drop_table('request_field_values')
    op.drop_table('renewals')
    op.drop_table('renewal_alerts')
    op.drop_table('portal_actions')
    op.drop_table('portal_access')
    op.drop_table('obligations')
    op.drop_table('form_field_validations')
    op.drop_table('form_field_options')
    op.drop_table('form_field_dependencies')
    op.drop_table('expiration_tracking')
    op.drop_table('dependency_responses')
    op.drop_table('dependency_comments')
    op.drop_table('dependency_attachments')
    op.drop_table('contract_versions')
    op.drop_table('contract_tokens')
    op.drop_table('compliance_reports')
    op.drop_table('client_portal_sessions')
    op.drop_table('client_feedback')
    op.drop_table('client_contracts_link')
    op.drop_table('archived_contracts')
    op.drop_table('amendments')
    op.drop_table('template_versions')
    op.drop_table('request_status_history')
    op.drop_table('request_comments')
    op.drop_table('request_clone_log')
    op.drop_table('request_attachments')
    op.drop_table('form_fields')
    op.drop_table('dependency_tasks')
    op.drop_table('contracts')
    op.drop_table('contract_manager_notes')
    op.drop_table('audit_log_details')
    op.drop_table('approval_workflow_steps')
    op.drop_table('user_roles')
    op.drop_table('user_login_history')
    op.drop_table('requests')
    op.drop_table('notification_preferences')
    op.drop_table('notification_logs')
    op.drop_table('form_versions')
    op.drop_table('form_publication_status')
    op.drop_table('form_categories')
    op.drop_table('contract_type_custom_fields')
    op.drop_table('contract_type_approval_rules')
    op.drop_table('contract_templates')
    op.drop_table('client_contacts')
    op.drop_table('client_addresses')
    op.drop_table('clause_versions')
    op.drop_table('audit_logs')
    op.drop_table('approval_workflows')
    op.drop_table('ai_queries')
    op.drop_table('ai_historical_benchmarks')
    op.drop_table('users')
    op.drop_table('template_clauses')
    op.drop_table('role_permissions')
    op.drop_table('request_forms')
    op.drop_table('integration_logs')
    op.drop_table('contract_types')
    op.drop_table('clients')
    op.drop_table('webhook_events')
    op.drop_table('subscription_history')
    op.drop_table('roles')
    op.drop_table('organization_settings')
    op.drop_table('notification_templates')
    op.drop_table('integration_configs')
    op.drop_table('departments')
    op.drop_table('contract_categories')
    op.drop_table('client_jurisdictions')
    op.drop_table('clause_categories')
    op.drop_table('approval_rejection_reasons')
    op.drop_table('analytics_views')
    op.drop_table('subscription_plans')
    op.drop_table('recycle_bin')
    op.drop_table('permanent_delete_log')
    op.drop_table('organizations')
    op.drop_table('deleted_records')
    op.drop_table('contract_token_sources')
    # ### end Alembic commands ###
