"""Add missing tables

Revision ID: ce4e04c021f4
Revises: 4288015eebf5
Create Date: 2026-08-13 12:08:49.464292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce4e04c021f4'
down_revision: Union[str, Sequence[str], None] = '4288015eebf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'last_redispatched_at')
    op.drop_column('contracts', 'version')
    op.drop_column('contracts', 'version_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('version_notes', mysql.TEXT(), nullable=True))
    op.add_column('contracts', sa.Column('version', mysql.VARCHAR(length=20), server_default=sa.text("'v1.0'"), nullable=True))
    op.add_column('contracts', sa.Column('last_redispatched_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
